name: Deploy to Droplet
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rsync to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='.git' --exclude='.github'
          path: .
          remote_path: /var/www/williampeoples135.site
          remote_host: ${{ secrets.DO_HOST }}
          remote_user: ${{ secrets.DO_USER }}
          remote_key: ${{ secrets.DO_KEY }}
